// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/int128/ghcp/usecases (interfaces: CommitToBranch,CreateBlobTreeCommit)

// Package mock_usecases is a generated GoMock package.
package mock_usecases

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	usecases "github.com/int128/ghcp/usecases"
	reflect "reflect"
)

// MockCommitToBranch is a mock of CommitToBranch interface
type MockCommitToBranch struct {
	ctrl     *gomock.Controller
	recorder *MockCommitToBranchMockRecorder
}

// MockCommitToBranchMockRecorder is the mock recorder for MockCommitToBranch
type MockCommitToBranchMockRecorder struct {
	mock *MockCommitToBranch
}

// NewMockCommitToBranch creates a new mock instance
func NewMockCommitToBranch(ctrl *gomock.Controller) *MockCommitToBranch {
	mock := &MockCommitToBranch{ctrl: ctrl}
	mock.recorder = &MockCommitToBranchMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockCommitToBranch) EXPECT() *MockCommitToBranchMockRecorder {
	return m.recorder
}

// Do mocks base method
func (m *MockCommitToBranch) Do(arg0 context.Context, arg1 usecases.CommitToBranchIn) error {
	ret := m.ctrl.Call(m, "Do", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Do indicates an expected call of Do
func (mr *MockCommitToBranchMockRecorder) Do(arg0, arg1 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*MockCommitToBranch)(nil).Do), arg0, arg1)
}

// MockCreateBlobTreeCommit is a mock of CreateBlobTreeCommit interface
type MockCreateBlobTreeCommit struct {
	ctrl     *gomock.Controller
	recorder *MockCreateBlobTreeCommitMockRecorder
}

// MockCreateBlobTreeCommitMockRecorder is the mock recorder for MockCreateBlobTreeCommit
type MockCreateBlobTreeCommitMockRecorder struct {
	mock *MockCreateBlobTreeCommit
}

// NewMockCreateBlobTreeCommit creates a new mock instance
func NewMockCreateBlobTreeCommit(ctrl *gomock.Controller) *MockCreateBlobTreeCommit {
	mock := &MockCreateBlobTreeCommit{ctrl: ctrl}
	mock.recorder = &MockCreateBlobTreeCommitMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockCreateBlobTreeCommit) EXPECT() *MockCreateBlobTreeCommitMockRecorder {
	return m.recorder
}

// Do mocks base method
func (m *MockCreateBlobTreeCommit) Do(arg0 context.Context, arg1 usecases.CreateBlobTreeCommitIn) (*usecases.CreateBlobTreeCommitOut, error) {
	ret := m.ctrl.Call(m, "Do", arg0, arg1)
	ret0, _ := ret[0].(*usecases.CreateBlobTreeCommitOut)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Do indicates an expected call of Do
func (mr *MockCreateBlobTreeCommitMockRecorder) Do(arg0, arg1 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*MockCreateBlobTreeCommit)(nil).Do), arg0, arg1)
}
