// Code generated by mockery v2.52.1. DO NOT EDIT.

package github_mock

import mock "github.com/stretchr/testify/mock"

// MockInternalBranchNodeID is an autogenerated mock type for the InternalBranchNodeID type
type MockInternalBranchNodeID struct {
	mock.Mock
}

type MockInternalBranchNodeID_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInternalBranchNodeID) EXPECT() *MockInternalBranchNodeID_Expecter {
	return &MockInternalBranchNodeID_Expecter{mock: &_m.Mock}
}

// NewMockInternalBranchNodeID creates a new instance of MockInternalBranchNodeID. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInternalBranchNodeID(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInternalBranchNodeID {
	mock := &MockInternalBranchNodeID{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
