// Code generated by mockery v2.53.4. DO NOT EDIT.

package github_mock

import mock "github.com/stretchr/testify/mock"

// MockInternalRepositoryNodeID is an autogenerated mock type for the InternalRepositoryNodeID type
type MockInternalRepositoryNodeID struct {
	mock.Mock
}

type MockInternalRepositoryNodeID_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInternalRepositoryNodeID) EXPECT() *MockInternalRepositoryNodeID_Expecter {
	return &MockInternalRepositoryNodeID_Expecter{mock: &_m.Mock}
}

// NewMockInternalRepositoryNodeID creates a new instance of MockInternalRepositoryNodeID. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInternalRepositoryNodeID(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInternalRepositoryNodeID {
	mock := &MockInternalRepositoryNodeID{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
