// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/int128/ghcp/pkg/cmd"
	"github.com/int128/ghcp/pkg/env"
	"github.com/int128/ghcp/pkg/fs"
	"github.com/int128/ghcp/pkg/github"
	"github.com/int128/ghcp/pkg/github/client"
	"github.com/int128/ghcp/pkg/logger"
	"github.com/int128/ghcp/pkg/usecases/commit"
	"github.com/int128/ghcp/pkg/usecases/forkcommit"
	"github.com/int128/ghcp/pkg/usecases/gitobject"
	"github.com/int128/ghcp/pkg/usecases/pullrequest"
	"github.com/int128/ghcp/pkg/usecases/release"
)

// Injectors from di.go:

func NewCmd() cmd.Interface {
	envEnv := &env.Env{}
	newFunc := _wireNewFuncValue
	clientNewFunc := _wireClientNewFuncValue
	newInternalRunnerFunc := _wireNewInternalRunnerFuncValue
	runner := &cmd.Runner{
		Env:               envEnv,
		NewLogger:         newFunc,
		NewGitHub:         clientNewFunc,
		NewInternalRunner: newInternalRunnerFunc,
	}
	return runner
}

var (
	_wireNewFuncValue               = logger.NewFunc(logger.New)
	_wireClientNewFuncValue         = client.NewFunc(client.New)
	_wireNewInternalRunnerFuncValue = cmd.NewInternalRunnerFunc(NewCmdInternalRunner)
)

func NewCmdInternalRunner(loggerInterface logger.Interface, clientInterface client.Interface) *cmd.InternalRunner {
	fileSystem := &fs.FileSystem{}
	gitHub := &github.GitHub{
		Client: clientInterface,
		Logger: loggerInterface,
	}
	createGitObject := &gitobject.CreateGitObject{
		FileSystem: fileSystem,
		Logger:     loggerInterface,
		GitHub:     gitHub,
	}
	commitCommit := &commit.Commit{
		CreateGitObject: createGitObject,
		FileSystem:      fileSystem,
		Logger:          loggerInterface,
		GitHub:          gitHub,
	}
	forkCommit := &forkcommit.ForkCommit{
		Commit: commitCommit,
		Logger: loggerInterface,
		GitHub: gitHub,
	}
	pullRequest := &pullrequest.PullRequest{
		GitHub: gitHub,
		Logger: loggerInterface,
	}
	releaseRelease := &release.Release{
		FileSystem: fileSystem,
		Logger:     loggerInterface,
		GitHub:     gitHub,
	}
	internalRunner := &cmd.InternalRunner{
		CommitUseCase:      commitCommit,
		ForkCommitUseCase:  forkCommit,
		PullRequestUseCase: pullRequest,
		ReleaseUseCase:     releaseRelease,
		Logger:             loggerInterface,
	}
	return internalRunner
}
