version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13.5
    steps:
      - run: mkdir -p ~/bin
      - run: echo 'export PATH="$HOME/bin:$PATH"' >> $BASH_ENV
      - run: curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b ~/bin v1.21.0
      - run: go get github.com/int128/goxzst
      - checkout
      - run: make check
      - run: bash <(curl -s https://codecov.io/bash)
      - run: make dist
      - run: |
          if [ "$CIRCLE_TAG" ]; then
            make release
          fi

workflows:
  version: 2
  all:
    jobs:
      - build:
          context: open-source
          filters:
            tags:
              only: /.*/
