version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11.2
    steps:
      - run: go get golang.org/x/lint/golint
      - run: go get github.com/mitchellh/gox
      - run: go get github.com/tcnksm/ghr
      - run: go get github.com/Songmu/ghch/cmd/ghch
      - checkout
      - run: make
      - run: |
          if [ "$CIRCLE_TAG" ]; then
            make release
          fi

workflows:
  version: 2
  all:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
