version: 2
jobs:
  build:
    docker:
      - image: cimg/go:1.15
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-sum-{{ checksum "go.sum" }}
      - run: make test
      - run: bash <(curl -s https://codecov.io/bash)
      - run:
          command: go get -v github.com/int128/goxzst
          working_directory: .circleci
      - run: make dist
      - run: |
          if [ "$CIRCLE_BRANCH" != master ]; then
            make acceptance-test
          fi
      - run: |
          if [ "$CIRCLE_TAG" ]; then
            make release
          fi
      - save_cache:
          key: go-sum-{{ checksum "go.sum" }}
          paths:
            - ~/go/pkg

workflows:
  version: 2
  all:
    jobs:
      - build:
          context: open-source
          filters:
            tags:
              only: /.*/
