version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11.2
    steps:
      - run: go get golang.org/x/lint/golint
      - run: go get github.com/mitchellh/gox
      - run: go get github.com/tcnksm/ghr
      - checkout
      - run: golint
      - run: go vet
      - run: go test -v ./...
      # Release to GitHub
      - run: |
          if [ "$CIRCLE_TAG" ]; then
            gox --osarch 'darwin/amd64 linux/amd64 windows/amd64' -output 'dist/{{.Dir}}_{{.OS}}_{{.Arch}}'
            ghr -u "$CIRCLE_PROJECT_USERNAME" -r "$CIRCLE_PROJECT_REPONAME" "$CIRCLE_TAG" dist
          fi
      # Release to Homebrew tap repository
      - run: |
          if [ "$CIRCLE_TAG" ]; then
            ./.circleci/homebrew.sh > dist/ghcp.rb
            cd dist
            ./ghcp_linux_amd64 -u "$CIRCLE_PROJECT_USERNAME" -r "homebrew-$CIRCLE_PROJECT_REPONAME" -m "$CIRCLE_TAG" ghcp.rb
          fi

workflows:
  version: 2
  all:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
