// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package client_mock

import (
	"context"
	"os"

	"github.com/google/go-github/v72/github"
	"github.com/shurcooL/githubv4"
	mock "github.com/stretchr/testify/mock"
)

// NewMockInterface creates a new instance of MockInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInterface {
	mock := &MockInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockInterface is an autogenerated mock type for the Interface type
type MockInterface struct {
	mock.Mock
}

type MockInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInterface) EXPECT() *MockInterface_Expecter {
	return &MockInterface_Expecter{mock: &_m.Mock}
}

// CreateBlob provides a mock function for the type MockInterface
func (_mock *MockInterface) CreateBlob(ctx context.Context, owner string, repo string, blob *github.Blob) (*github.Blob, *github.Response, error) {
	ret := _mock.Called(ctx, owner, repo, blob)

	if len(ret) == 0 {
		panic("no return value specified for CreateBlob")
	}

	var r0 *github.Blob
	var r1 *github.Response
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *github.Blob) (*github.Blob, *github.Response, error)); ok {
		return returnFunc(ctx, owner, repo, blob)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *github.Blob) *github.Blob); ok {
		r0 = returnFunc(ctx, owner, repo, blob)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*github.Blob)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, *github.Blob) *github.Response); ok {
		r1 = returnFunc(ctx, owner, repo, blob)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*github.Response)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string, *github.Blob) error); ok {
		r2 = returnFunc(ctx, owner, repo, blob)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockInterface_CreateBlob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBlob'
type MockInterface_CreateBlob_Call struct {
	*mock.Call
}

// CreateBlob is a helper method to define mock.On call
//   - ctx context.Context
//   - owner string
//   - repo string
//   - blob *github.Blob
func (_e *MockInterface_Expecter) CreateBlob(ctx interface{}, owner interface{}, repo interface{}, blob interface{}) *MockInterface_CreateBlob_Call {
	return &MockInterface_CreateBlob_Call{Call: _e.mock.On("CreateBlob", ctx, owner, repo, blob)}
}

func (_c *MockInterface_CreateBlob_Call) Run(run func(ctx context.Context, owner string, repo string, blob *github.Blob)) *MockInterface_CreateBlob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 *github.Blob
		if args[3] != nil {
			arg3 = args[3].(*github.Blob)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockInterface_CreateBlob_Call) Return(blob1 *github.Blob, response *github.Response, err error) *MockInterface_CreateBlob_Call {
	_c.Call.Return(blob1, response, err)
	return _c
}

func (_c *MockInterface_CreateBlob_Call) RunAndReturn(run func(ctx context.Context, owner string, repo string, blob *github.Blob) (*github.Blob, *github.Response, error)) *MockInterface_CreateBlob_Call {
	_c.Call.Return(run)
	return _c
}

// CreateCommit provides a mock function for the type MockInterface
func (_mock *MockInterface) CreateCommit(ctx context.Context, owner string, repo string, commit *github.Commit, opts *github.CreateCommitOptions) (*github.Commit, *github.Response, error) {
	ret := _mock.Called(ctx, owner, repo, commit, opts)

	if len(ret) == 0 {
		panic("no return value specified for CreateCommit")
	}

	var r0 *github.Commit
	var r1 *github.Response
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *github.Commit, *github.CreateCommitOptions) (*github.Commit, *github.Response, error)); ok {
		return returnFunc(ctx, owner, repo, commit, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *github.Commit, *github.CreateCommitOptions) *github.Commit); ok {
		r0 = returnFunc(ctx, owner, repo, commit, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*github.Commit)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, *github.Commit, *github.CreateCommitOptions) *github.Response); ok {
		r1 = returnFunc(ctx, owner, repo, commit, opts)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*github.Response)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string, *github.Commit, *github.CreateCommitOptions) error); ok {
		r2 = returnFunc(ctx, owner, repo, commit, opts)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockInterface_CreateCommit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateCommit'
type MockInterface_CreateCommit_Call struct {
	*mock.Call
}

// CreateCommit is a helper method to define mock.On call
//   - ctx context.Context
//   - owner string
//   - repo string
//   - commit *github.Commit
//   - opts *github.CreateCommitOptions
func (_e *MockInterface_Expecter) CreateCommit(ctx interface{}, owner interface{}, repo interface{}, commit interface{}, opts interface{}) *MockInterface_CreateCommit_Call {
	return &MockInterface_CreateCommit_Call{Call: _e.mock.On("CreateCommit", ctx, owner, repo, commit, opts)}
}

func (_c *MockInterface_CreateCommit_Call) Run(run func(ctx context.Context, owner string, repo string, commit *github.Commit, opts *github.CreateCommitOptions)) *MockInterface_CreateCommit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 *github.Commit
		if args[3] != nil {
			arg3 = args[3].(*github.Commit)
		}
		var arg4 *github.CreateCommitOptions
		if args[4] != nil {
			arg4 = args[4].(*github.CreateCommitOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockInterface_CreateCommit_Call) Return(commit1 *github.Commit, response *github.Response, err error) *MockInterface_CreateCommit_Call {
	_c.Call.Return(commit1, response, err)
	return _c
}

func (_c *MockInterface_CreateCommit_Call) RunAndReturn(run func(ctx context.Context, owner string, repo string, commit *github.Commit, opts *github.CreateCommitOptions) (*github.Commit, *github.Response, error)) *MockInterface_CreateCommit_Call {
	_c.Call.Return(run)
	return _c
}

// CreateFork provides a mock function for the type MockInterface
func (_mock *MockInterface) CreateFork(ctx context.Context, owner string, repo string, opt *github.RepositoryCreateForkOptions) (*github.Repository, *github.Response, error) {
	ret := _mock.Called(ctx, owner, repo, opt)

	if len(ret) == 0 {
		panic("no return value specified for CreateFork")
	}

	var r0 *github.Repository
	var r1 *github.Response
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *github.RepositoryCreateForkOptions) (*github.Repository, *github.Response, error)); ok {
		return returnFunc(ctx, owner, repo, opt)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *github.RepositoryCreateForkOptions) *github.Repository); ok {
		r0 = returnFunc(ctx, owner, repo, opt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*github.Repository)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, *github.RepositoryCreateForkOptions) *github.Response); ok {
		r1 = returnFunc(ctx, owner, repo, opt)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*github.Response)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string, *github.RepositoryCreateForkOptions) error); ok {
		r2 = returnFunc(ctx, owner, repo, opt)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockInterface_CreateFork_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateFork'
type MockInterface_CreateFork_Call struct {
	*mock.Call
}

// CreateFork is a helper method to define mock.On call
//   - ctx context.Context
//   - owner string
//   - repo string
//   - opt *github.RepositoryCreateForkOptions
func (_e *MockInterface_Expecter) CreateFork(ctx interface{}, owner interface{}, repo interface{}, opt interface{}) *MockInterface_CreateFork_Call {
	return &MockInterface_CreateFork_Call{Call: _e.mock.On("CreateFork", ctx, owner, repo, opt)}
}

func (_c *MockInterface_CreateFork_Call) Run(run func(ctx context.Context, owner string, repo string, opt *github.RepositoryCreateForkOptions)) *MockInterface_CreateFork_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 *github.RepositoryCreateForkOptions
		if args[3] != nil {
			arg3 = args[3].(*github.RepositoryCreateForkOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockInterface_CreateFork_Call) Return(repository *github.Repository, response *github.Response, err error) *MockInterface_CreateFork_Call {
	_c.Call.Return(repository, response, err)
	return _c
}

func (_c *MockInterface_CreateFork_Call) RunAndReturn(run func(ctx context.Context, owner string, repo string, opt *github.RepositoryCreateForkOptions) (*github.Repository, *github.Response, error)) *MockInterface_CreateFork_Call {
	_c.Call.Return(run)
	return _c
}

// CreateRelease provides a mock function for the type MockInterface
func (_mock *MockInterface) CreateRelease(ctx context.Context, owner string, repo string, release *github.RepositoryRelease) (*github.RepositoryRelease, *github.Response, error) {
	ret := _mock.Called(ctx, owner, repo, release)

	if len(ret) == 0 {
		panic("no return value specified for CreateRelease")
	}

	var r0 *github.RepositoryRelease
	var r1 *github.Response
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *github.RepositoryRelease) (*github.RepositoryRelease, *github.Response, error)); ok {
		return returnFunc(ctx, owner, repo, release)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *github.RepositoryRelease) *github.RepositoryRelease); ok {
		r0 = returnFunc(ctx, owner, repo, release)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*github.RepositoryRelease)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, *github.RepositoryRelease) *github.Response); ok {
		r1 = returnFunc(ctx, owner, repo, release)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*github.Response)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string, *github.RepositoryRelease) error); ok {
		r2 = returnFunc(ctx, owner, repo, release)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockInterface_CreateRelease_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRelease'
type MockInterface_CreateRelease_Call struct {
	*mock.Call
}

// CreateRelease is a helper method to define mock.On call
//   - ctx context.Context
//   - owner string
//   - repo string
//   - release *github.RepositoryRelease
func (_e *MockInterface_Expecter) CreateRelease(ctx interface{}, owner interface{}, repo interface{}, release interface{}) *MockInterface_CreateRelease_Call {
	return &MockInterface_CreateRelease_Call{Call: _e.mock.On("CreateRelease", ctx, owner, repo, release)}
}

func (_c *MockInterface_CreateRelease_Call) Run(run func(ctx context.Context, owner string, repo string, release *github.RepositoryRelease)) *MockInterface_CreateRelease_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 *github.RepositoryRelease
		if args[3] != nil {
			arg3 = args[3].(*github.RepositoryRelease)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockInterface_CreateRelease_Call) Return(repositoryRelease *github.RepositoryRelease, response *github.Response, err error) *MockInterface_CreateRelease_Call {
	_c.Call.Return(repositoryRelease, response, err)
	return _c
}

func (_c *MockInterface_CreateRelease_Call) RunAndReturn(run func(ctx context.Context, owner string, repo string, release *github.RepositoryRelease) (*github.RepositoryRelease, *github.Response, error)) *MockInterface_CreateRelease_Call {
	_c.Call.Return(run)
	return _c
}

// CreateTree provides a mock function for the type MockInterface
func (_mock *MockInterface) CreateTree(ctx context.Context, owner string, repo string, baseTree string, entries []*github.TreeEntry) (*github.Tree, *github.Response, error) {
	ret := _mock.Called(ctx, owner, repo, baseTree, entries)

	if len(ret) == 0 {
		panic("no return value specified for CreateTree")
	}

	var r0 *github.Tree
	var r1 *github.Response
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, []*github.TreeEntry) (*github.Tree, *github.Response, error)); ok {
		return returnFunc(ctx, owner, repo, baseTree, entries)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, []*github.TreeEntry) *github.Tree); ok {
		r0 = returnFunc(ctx, owner, repo, baseTree, entries)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*github.Tree)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, []*github.TreeEntry) *github.Response); ok {
		r1 = returnFunc(ctx, owner, repo, baseTree, entries)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*github.Response)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string, string, []*github.TreeEntry) error); ok {
		r2 = returnFunc(ctx, owner, repo, baseTree, entries)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockInterface_CreateTree_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTree'
type MockInterface_CreateTree_Call struct {
	*mock.Call
}

// CreateTree is a helper method to define mock.On call
//   - ctx context.Context
//   - owner string
//   - repo string
//   - baseTree string
//   - entries []*github.TreeEntry
func (_e *MockInterface_Expecter) CreateTree(ctx interface{}, owner interface{}, repo interface{}, baseTree interface{}, entries interface{}) *MockInterface_CreateTree_Call {
	return &MockInterface_CreateTree_Call{Call: _e.mock.On("CreateTree", ctx, owner, repo, baseTree, entries)}
}

func (_c *MockInterface_CreateTree_Call) Run(run func(ctx context.Context, owner string, repo string, baseTree string, entries []*github.TreeEntry)) *MockInterface_CreateTree_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 []*github.TreeEntry
		if args[4] != nil {
			arg4 = args[4].([]*github.TreeEntry)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockInterface_CreateTree_Call) Return(tree *github.Tree, response *github.Response, err error) *MockInterface_CreateTree_Call {
	_c.Call.Return(tree, response, err)
	return _c
}

func (_c *MockInterface_CreateTree_Call) RunAndReturn(run func(ctx context.Context, owner string, repo string, baseTree string, entries []*github.TreeEntry) (*github.Tree, *github.Response, error)) *MockInterface_CreateTree_Call {
	_c.Call.Return(run)
	return _c
}

// GetReleaseByTag provides a mock function for the type MockInterface
func (_mock *MockInterface) GetReleaseByTag(ctx context.Context, owner string, repo string, tag string) (*github.RepositoryRelease, *github.Response, error) {
	ret := _mock.Called(ctx, owner, repo, tag)

	if len(ret) == 0 {
		panic("no return value specified for GetReleaseByTag")
	}

	var r0 *github.RepositoryRelease
	var r1 *github.Response
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (*github.RepositoryRelease, *github.Response, error)); ok {
		return returnFunc(ctx, owner, repo, tag)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) *github.RepositoryRelease); ok {
		r0 = returnFunc(ctx, owner, repo, tag)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*github.RepositoryRelease)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) *github.Response); ok {
		r1 = returnFunc(ctx, owner, repo, tag)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*github.Response)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string, string) error); ok {
		r2 = returnFunc(ctx, owner, repo, tag)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockInterface_GetReleaseByTag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetReleaseByTag'
type MockInterface_GetReleaseByTag_Call struct {
	*mock.Call
}

// GetReleaseByTag is a helper method to define mock.On call
//   - ctx context.Context
//   - owner string
//   - repo string
//   - tag string
func (_e *MockInterface_Expecter) GetReleaseByTag(ctx interface{}, owner interface{}, repo interface{}, tag interface{}) *MockInterface_GetReleaseByTag_Call {
	return &MockInterface_GetReleaseByTag_Call{Call: _e.mock.On("GetReleaseByTag", ctx, owner, repo, tag)}
}

func (_c *MockInterface_GetReleaseByTag_Call) Run(run func(ctx context.Context, owner string, repo string, tag string)) *MockInterface_GetReleaseByTag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockInterface_GetReleaseByTag_Call) Return(repositoryRelease *github.RepositoryRelease, response *github.Response, err error) *MockInterface_GetReleaseByTag_Call {
	_c.Call.Return(repositoryRelease, response, err)
	return _c
}

func (_c *MockInterface_GetReleaseByTag_Call) RunAndReturn(run func(ctx context.Context, owner string, repo string, tag string) (*github.RepositoryRelease, *github.Response, error)) *MockInterface_GetReleaseByTag_Call {
	_c.Call.Return(run)
	return _c
}

// Mutate provides a mock function for the type MockInterface
func (_mock *MockInterface) Mutate(ctx context.Context, m interface{}, input githubv4.Input, variables map[string]interface{}) error {
	ret := _mock.Called(ctx, m, input, variables)

	if len(ret) == 0 {
		panic("no return value specified for Mutate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, interface{}, githubv4.Input, map[string]interface{}) error); ok {
		r0 = returnFunc(ctx, m, input, variables)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockInterface_Mutate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Mutate'
type MockInterface_Mutate_Call struct {
	*mock.Call
}

// Mutate is a helper method to define mock.On call
//   - ctx context.Context
//   - m interface{}
//   - input githubv4.Input
//   - variables map[string]interface{}
func (_e *MockInterface_Expecter) Mutate(ctx interface{}, m interface{}, input interface{}, variables interface{}) *MockInterface_Mutate_Call {
	return &MockInterface_Mutate_Call{Call: _e.mock.On("Mutate", ctx, m, input, variables)}
}

func (_c *MockInterface_Mutate_Call) Run(run func(ctx context.Context, m interface{}, input githubv4.Input, variables map[string]interface{})) *MockInterface_Mutate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 interface{}
		if args[1] != nil {
			arg1 = args[1].(interface{})
		}
		var arg2 githubv4.Input
		if args[2] != nil {
			arg2 = args[2].(githubv4.Input)
		}
		var arg3 map[string]interface{}
		if args[3] != nil {
			arg3 = args[3].(map[string]interface{})
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockInterface_Mutate_Call) Return(err error) *MockInterface_Mutate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockInterface_Mutate_Call) RunAndReturn(run func(ctx context.Context, m interface{}, input githubv4.Input, variables map[string]interface{}) error) *MockInterface_Mutate_Call {
	_c.Call.Return(run)
	return _c
}

// Query provides a mock function for the type MockInterface
func (_mock *MockInterface) Query(ctx context.Context, q interface{}, variables map[string]interface{}) error {
	ret := _mock.Called(ctx, q, variables)

	if len(ret) == 0 {
		panic("no return value specified for Query")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, interface{}, map[string]interface{}) error); ok {
		r0 = returnFunc(ctx, q, variables)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockInterface_Query_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Query'
type MockInterface_Query_Call struct {
	*mock.Call
}

// Query is a helper method to define mock.On call
//   - ctx context.Context
//   - q interface{}
//   - variables map[string]interface{}
func (_e *MockInterface_Expecter) Query(ctx interface{}, q interface{}, variables interface{}) *MockInterface_Query_Call {
	return &MockInterface_Query_Call{Call: _e.mock.On("Query", ctx, q, variables)}
}

func (_c *MockInterface_Query_Call) Run(run func(ctx context.Context, q interface{}, variables map[string]interface{})) *MockInterface_Query_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 interface{}
		if args[1] != nil {
			arg1 = args[1].(interface{})
		}
		var arg2 map[string]interface{}
		if args[2] != nil {
			arg2 = args[2].(map[string]interface{})
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockInterface_Query_Call) Return(err error) *MockInterface_Query_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockInterface_Query_Call) RunAndReturn(run func(ctx context.Context, q interface{}, variables map[string]interface{}) error) *MockInterface_Query_Call {
	_c.Call.Return(run)
	return _c
}

// UploadReleaseAsset provides a mock function for the type MockInterface
func (_mock *MockInterface) UploadReleaseAsset(ctx context.Context, owner string, repo string, id int64, opt *github.UploadOptions, file *os.File) (*github.ReleaseAsset, *github.Response, error) {
	ret := _mock.Called(ctx, owner, repo, id, opt, file)

	if len(ret) == 0 {
		panic("no return value specified for UploadReleaseAsset")
	}

	var r0 *github.ReleaseAsset
	var r1 *github.Response
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int64, *github.UploadOptions, *os.File) (*github.ReleaseAsset, *github.Response, error)); ok {
		return returnFunc(ctx, owner, repo, id, opt, file)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int64, *github.UploadOptions, *os.File) *github.ReleaseAsset); ok {
		r0 = returnFunc(ctx, owner, repo, id, opt, file)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*github.ReleaseAsset)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, int64, *github.UploadOptions, *os.File) *github.Response); ok {
		r1 = returnFunc(ctx, owner, repo, id, opt, file)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*github.Response)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string, int64, *github.UploadOptions, *os.File) error); ok {
		r2 = returnFunc(ctx, owner, repo, id, opt, file)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockInterface_UploadReleaseAsset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadReleaseAsset'
type MockInterface_UploadReleaseAsset_Call struct {
	*mock.Call
}

// UploadReleaseAsset is a helper method to define mock.On call
//   - ctx context.Context
//   - owner string
//   - repo string
//   - id int64
//   - opt *github.UploadOptions
//   - file *os.File
func (_e *MockInterface_Expecter) UploadReleaseAsset(ctx interface{}, owner interface{}, repo interface{}, id interface{}, opt interface{}, file interface{}) *MockInterface_UploadReleaseAsset_Call {
	return &MockInterface_UploadReleaseAsset_Call{Call: _e.mock.On("UploadReleaseAsset", ctx, owner, repo, id, opt, file)}
}

func (_c *MockInterface_UploadReleaseAsset_Call) Run(run func(ctx context.Context, owner string, repo string, id int64, opt *github.UploadOptions, file *os.File)) *MockInterface_UploadReleaseAsset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		var arg4 *github.UploadOptions
		if args[4] != nil {
			arg4 = args[4].(*github.UploadOptions)
		}
		var arg5 *os.File
		if args[5] != nil {
			arg5 = args[5].(*os.File)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockInterface_UploadReleaseAsset_Call) Return(releaseAsset *github.ReleaseAsset, response *github.Response, err error) *MockInterface_UploadReleaseAsset_Call {
	_c.Call.Return(releaseAsset, response, err)
	return _c
}

func (_c *MockInterface_UploadReleaseAsset_Call) RunAndReturn(run func(ctx context.Context, owner string, repo string, id int64, opt *github.UploadOptions, file *os.File) (*github.ReleaseAsset, *github.Response, error)) *MockInterface_UploadReleaseAsset_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockQueryService creates a new instance of MockQueryService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQueryService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQueryService {
	mock := &MockQueryService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockQueryService is an autogenerated mock type for the QueryService type
type MockQueryService struct {
	mock.Mock
}

type MockQueryService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQueryService) EXPECT() *MockQueryService_Expecter {
	return &MockQueryService_Expecter{mock: &_m.Mock}
}

// Mutate provides a mock function for the type MockQueryService
func (_mock *MockQueryService) Mutate(ctx context.Context, m interface{}, input githubv4.Input, variables map[string]interface{}) error {
	ret := _mock.Called(ctx, m, input, variables)

	if len(ret) == 0 {
		panic("no return value specified for Mutate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, interface{}, githubv4.Input, map[string]interface{}) error); ok {
		r0 = returnFunc(ctx, m, input, variables)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQueryService_Mutate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Mutate'
type MockQueryService_Mutate_Call struct {
	*mock.Call
}

// Mutate is a helper method to define mock.On call
//   - ctx context.Context
//   - m interface{}
//   - input githubv4.Input
//   - variables map[string]interface{}
func (_e *MockQueryService_Expecter) Mutate(ctx interface{}, m interface{}, input interface{}, variables interface{}) *MockQueryService_Mutate_Call {
	return &MockQueryService_Mutate_Call{Call: _e.mock.On("Mutate", ctx, m, input, variables)}
}

func (_c *MockQueryService_Mutate_Call) Run(run func(ctx context.Context, m interface{}, input githubv4.Input, variables map[string]interface{})) *MockQueryService_Mutate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 interface{}
		if args[1] != nil {
			arg1 = args[1].(interface{})
		}
		var arg2 githubv4.Input
		if args[2] != nil {
			arg2 = args[2].(githubv4.Input)
		}
		var arg3 map[string]interface{}
		if args[3] != nil {
			arg3 = args[3].(map[string]interface{})
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockQueryService_Mutate_Call) Return(err error) *MockQueryService_Mutate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQueryService_Mutate_Call) RunAndReturn(run func(ctx context.Context, m interface{}, input githubv4.Input, variables map[string]interface{}) error) *MockQueryService_Mutate_Call {
	_c.Call.Return(run)
	return _c
}

// Query provides a mock function for the type MockQueryService
func (_mock *MockQueryService) Query(ctx context.Context, q interface{}, variables map[string]interface{}) error {
	ret := _mock.Called(ctx, q, variables)

	if len(ret) == 0 {
		panic("no return value specified for Query")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, interface{}, map[string]interface{}) error); ok {
		r0 = returnFunc(ctx, q, variables)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQueryService_Query_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Query'
type MockQueryService_Query_Call struct {
	*mock.Call
}

// Query is a helper method to define mock.On call
//   - ctx context.Context
//   - q interface{}
//   - variables map[string]interface{}
func (_e *MockQueryService_Expecter) Query(ctx interface{}, q interface{}, variables interface{}) *MockQueryService_Query_Call {
	return &MockQueryService_Query_Call{Call: _e.mock.On("Query", ctx, q, variables)}
}

func (_c *MockQueryService_Query_Call) Run(run func(ctx context.Context, q interface{}, variables map[string]interface{})) *MockQueryService_Query_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 interface{}
		if args[1] != nil {
			arg1 = args[1].(interface{})
		}
		var arg2 map[string]interface{}
		if args[2] != nil {
			arg2 = args[2].(map[string]interface{})
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockQueryService_Query_Call) Return(err error) *MockQueryService_Query_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQueryService_Query_Call) RunAndReturn(run func(ctx context.Context, q interface{}, variables map[string]interface{}) error) *MockQueryService_Query_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGitService creates a new instance of MockGitService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGitService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGitService {
	mock := &MockGitService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGitService is an autogenerated mock type for the GitService type
type MockGitService struct {
	mock.Mock
}

type MockGitService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGitService) EXPECT() *MockGitService_Expecter {
	return &MockGitService_Expecter{mock: &_m.Mock}
}

// CreateBlob provides a mock function for the type MockGitService
func (_mock *MockGitService) CreateBlob(ctx context.Context, owner string, repo string, blob *github.Blob) (*github.Blob, *github.Response, error) {
	ret := _mock.Called(ctx, owner, repo, blob)

	if len(ret) == 0 {
		panic("no return value specified for CreateBlob")
	}

	var r0 *github.Blob
	var r1 *github.Response
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *github.Blob) (*github.Blob, *github.Response, error)); ok {
		return returnFunc(ctx, owner, repo, blob)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *github.Blob) *github.Blob); ok {
		r0 = returnFunc(ctx, owner, repo, blob)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*github.Blob)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, *github.Blob) *github.Response); ok {
		r1 = returnFunc(ctx, owner, repo, blob)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*github.Response)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string, *github.Blob) error); ok {
		r2 = returnFunc(ctx, owner, repo, blob)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockGitService_CreateBlob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBlob'
type MockGitService_CreateBlob_Call struct {
	*mock.Call
}

// CreateBlob is a helper method to define mock.On call
//   - ctx context.Context
//   - owner string
//   - repo string
//   - blob *github.Blob
func (_e *MockGitService_Expecter) CreateBlob(ctx interface{}, owner interface{}, repo interface{}, blob interface{}) *MockGitService_CreateBlob_Call {
	return &MockGitService_CreateBlob_Call{Call: _e.mock.On("CreateBlob", ctx, owner, repo, blob)}
}

func (_c *MockGitService_CreateBlob_Call) Run(run func(ctx context.Context, owner string, repo string, blob *github.Blob)) *MockGitService_CreateBlob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 *github.Blob
		if args[3] != nil {
			arg3 = args[3].(*github.Blob)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockGitService_CreateBlob_Call) Return(blob1 *github.Blob, response *github.Response, err error) *MockGitService_CreateBlob_Call {
	_c.Call.Return(blob1, response, err)
	return _c
}

func (_c *MockGitService_CreateBlob_Call) RunAndReturn(run func(ctx context.Context, owner string, repo string, blob *github.Blob) (*github.Blob, *github.Response, error)) *MockGitService_CreateBlob_Call {
	_c.Call.Return(run)
	return _c
}

// CreateCommit provides a mock function for the type MockGitService
func (_mock *MockGitService) CreateCommit(ctx context.Context, owner string, repo string, commit *github.Commit, opts *github.CreateCommitOptions) (*github.Commit, *github.Response, error) {
	ret := _mock.Called(ctx, owner, repo, commit, opts)

	if len(ret) == 0 {
		panic("no return value specified for CreateCommit")
	}

	var r0 *github.Commit
	var r1 *github.Response
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *github.Commit, *github.CreateCommitOptions) (*github.Commit, *github.Response, error)); ok {
		return returnFunc(ctx, owner, repo, commit, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *github.Commit, *github.CreateCommitOptions) *github.Commit); ok {
		r0 = returnFunc(ctx, owner, repo, commit, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*github.Commit)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, *github.Commit, *github.CreateCommitOptions) *github.Response); ok {
		r1 = returnFunc(ctx, owner, repo, commit, opts)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*github.Response)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string, *github.Commit, *github.CreateCommitOptions) error); ok {
		r2 = returnFunc(ctx, owner, repo, commit, opts)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockGitService_CreateCommit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateCommit'
type MockGitService_CreateCommit_Call struct {
	*mock.Call
}

// CreateCommit is a helper method to define mock.On call
//   - ctx context.Context
//   - owner string
//   - repo string
//   - commit *github.Commit
//   - opts *github.CreateCommitOptions
func (_e *MockGitService_Expecter) CreateCommit(ctx interface{}, owner interface{}, repo interface{}, commit interface{}, opts interface{}) *MockGitService_CreateCommit_Call {
	return &MockGitService_CreateCommit_Call{Call: _e.mock.On("CreateCommit", ctx, owner, repo, commit, opts)}
}

func (_c *MockGitService_CreateCommit_Call) Run(run func(ctx context.Context, owner string, repo string, commit *github.Commit, opts *github.CreateCommitOptions)) *MockGitService_CreateCommit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 *github.Commit
		if args[3] != nil {
			arg3 = args[3].(*github.Commit)
		}
		var arg4 *github.CreateCommitOptions
		if args[4] != nil {
			arg4 = args[4].(*github.CreateCommitOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockGitService_CreateCommit_Call) Return(commit1 *github.Commit, response *github.Response, err error) *MockGitService_CreateCommit_Call {
	_c.Call.Return(commit1, response, err)
	return _c
}

func (_c *MockGitService_CreateCommit_Call) RunAndReturn(run func(ctx context.Context, owner string, repo string, commit *github.Commit, opts *github.CreateCommitOptions) (*github.Commit, *github.Response, error)) *MockGitService_CreateCommit_Call {
	_c.Call.Return(run)
	return _c
}

// CreateTree provides a mock function for the type MockGitService
func (_mock *MockGitService) CreateTree(ctx context.Context, owner string, repo string, baseTree string, entries []*github.TreeEntry) (*github.Tree, *github.Response, error) {
	ret := _mock.Called(ctx, owner, repo, baseTree, entries)

	if len(ret) == 0 {
		panic("no return value specified for CreateTree")
	}

	var r0 *github.Tree
	var r1 *github.Response
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, []*github.TreeEntry) (*github.Tree, *github.Response, error)); ok {
		return returnFunc(ctx, owner, repo, baseTree, entries)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, []*github.TreeEntry) *github.Tree); ok {
		r0 = returnFunc(ctx, owner, repo, baseTree, entries)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*github.Tree)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, []*github.TreeEntry) *github.Response); ok {
		r1 = returnFunc(ctx, owner, repo, baseTree, entries)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*github.Response)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string, string, []*github.TreeEntry) error); ok {
		r2 = returnFunc(ctx, owner, repo, baseTree, entries)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockGitService_CreateTree_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTree'
type MockGitService_CreateTree_Call struct {
	*mock.Call
}

// CreateTree is a helper method to define mock.On call
//   - ctx context.Context
//   - owner string
//   - repo string
//   - baseTree string
//   - entries []*github.TreeEntry
func (_e *MockGitService_Expecter) CreateTree(ctx interface{}, owner interface{}, repo interface{}, baseTree interface{}, entries interface{}) *MockGitService_CreateTree_Call {
	return &MockGitService_CreateTree_Call{Call: _e.mock.On("CreateTree", ctx, owner, repo, baseTree, entries)}
}

func (_c *MockGitService_CreateTree_Call) Run(run func(ctx context.Context, owner string, repo string, baseTree string, entries []*github.TreeEntry)) *MockGitService_CreateTree_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 []*github.TreeEntry
		if args[4] != nil {
			arg4 = args[4].([]*github.TreeEntry)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockGitService_CreateTree_Call) Return(tree *github.Tree, response *github.Response, err error) *MockGitService_CreateTree_Call {
	_c.Call.Return(tree, response, err)
	return _c
}

func (_c *MockGitService_CreateTree_Call) RunAndReturn(run func(ctx context.Context, owner string, repo string, baseTree string, entries []*github.TreeEntry) (*github.Tree, *github.Response, error)) *MockGitService_CreateTree_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepositoriesService creates a new instance of MockRepositoriesService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepositoriesService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepositoriesService {
	mock := &MockRepositoriesService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepositoriesService is an autogenerated mock type for the RepositoriesService type
type MockRepositoriesService struct {
	mock.Mock
}

type MockRepositoriesService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepositoriesService) EXPECT() *MockRepositoriesService_Expecter {
	return &MockRepositoriesService_Expecter{mock: &_m.Mock}
}

// CreateFork provides a mock function for the type MockRepositoriesService
func (_mock *MockRepositoriesService) CreateFork(ctx context.Context, owner string, repo string, opt *github.RepositoryCreateForkOptions) (*github.Repository, *github.Response, error) {
	ret := _mock.Called(ctx, owner, repo, opt)

	if len(ret) == 0 {
		panic("no return value specified for CreateFork")
	}

	var r0 *github.Repository
	var r1 *github.Response
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *github.RepositoryCreateForkOptions) (*github.Repository, *github.Response, error)); ok {
		return returnFunc(ctx, owner, repo, opt)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *github.RepositoryCreateForkOptions) *github.Repository); ok {
		r0 = returnFunc(ctx, owner, repo, opt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*github.Repository)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, *github.RepositoryCreateForkOptions) *github.Response); ok {
		r1 = returnFunc(ctx, owner, repo, opt)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*github.Response)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string, *github.RepositoryCreateForkOptions) error); ok {
		r2 = returnFunc(ctx, owner, repo, opt)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockRepositoriesService_CreateFork_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateFork'
type MockRepositoriesService_CreateFork_Call struct {
	*mock.Call
}

// CreateFork is a helper method to define mock.On call
//   - ctx context.Context
//   - owner string
//   - repo string
//   - opt *github.RepositoryCreateForkOptions
func (_e *MockRepositoriesService_Expecter) CreateFork(ctx interface{}, owner interface{}, repo interface{}, opt interface{}) *MockRepositoriesService_CreateFork_Call {
	return &MockRepositoriesService_CreateFork_Call{Call: _e.mock.On("CreateFork", ctx, owner, repo, opt)}
}

func (_c *MockRepositoriesService_CreateFork_Call) Run(run func(ctx context.Context, owner string, repo string, opt *github.RepositoryCreateForkOptions)) *MockRepositoriesService_CreateFork_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 *github.RepositoryCreateForkOptions
		if args[3] != nil {
			arg3 = args[3].(*github.RepositoryCreateForkOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRepositoriesService_CreateFork_Call) Return(repository *github.Repository, response *github.Response, err error) *MockRepositoriesService_CreateFork_Call {
	_c.Call.Return(repository, response, err)
	return _c
}

func (_c *MockRepositoriesService_CreateFork_Call) RunAndReturn(run func(ctx context.Context, owner string, repo string, opt *github.RepositoryCreateForkOptions) (*github.Repository, *github.Response, error)) *MockRepositoriesService_CreateFork_Call {
	_c.Call.Return(run)
	return _c
}

// CreateRelease provides a mock function for the type MockRepositoriesService
func (_mock *MockRepositoriesService) CreateRelease(ctx context.Context, owner string, repo string, release *github.RepositoryRelease) (*github.RepositoryRelease, *github.Response, error) {
	ret := _mock.Called(ctx, owner, repo, release)

	if len(ret) == 0 {
		panic("no return value specified for CreateRelease")
	}

	var r0 *github.RepositoryRelease
	var r1 *github.Response
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *github.RepositoryRelease) (*github.RepositoryRelease, *github.Response, error)); ok {
		return returnFunc(ctx, owner, repo, release)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *github.RepositoryRelease) *github.RepositoryRelease); ok {
		r0 = returnFunc(ctx, owner, repo, release)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*github.RepositoryRelease)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, *github.RepositoryRelease) *github.Response); ok {
		r1 = returnFunc(ctx, owner, repo, release)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*github.Response)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string, *github.RepositoryRelease) error); ok {
		r2 = returnFunc(ctx, owner, repo, release)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockRepositoriesService_CreateRelease_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRelease'
type MockRepositoriesService_CreateRelease_Call struct {
	*mock.Call
}

// CreateRelease is a helper method to define mock.On call
//   - ctx context.Context
//   - owner string
//   - repo string
//   - release *github.RepositoryRelease
func (_e *MockRepositoriesService_Expecter) CreateRelease(ctx interface{}, owner interface{}, repo interface{}, release interface{}) *MockRepositoriesService_CreateRelease_Call {
	return &MockRepositoriesService_CreateRelease_Call{Call: _e.mock.On("CreateRelease", ctx, owner, repo, release)}
}

func (_c *MockRepositoriesService_CreateRelease_Call) Run(run func(ctx context.Context, owner string, repo string, release *github.RepositoryRelease)) *MockRepositoriesService_CreateRelease_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 *github.RepositoryRelease
		if args[3] != nil {
			arg3 = args[3].(*github.RepositoryRelease)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRepositoriesService_CreateRelease_Call) Return(repositoryRelease *github.RepositoryRelease, response *github.Response, err error) *MockRepositoriesService_CreateRelease_Call {
	_c.Call.Return(repositoryRelease, response, err)
	return _c
}

func (_c *MockRepositoriesService_CreateRelease_Call) RunAndReturn(run func(ctx context.Context, owner string, repo string, release *github.RepositoryRelease) (*github.RepositoryRelease, *github.Response, error)) *MockRepositoriesService_CreateRelease_Call {
	_c.Call.Return(run)
	return _c
}

// GetReleaseByTag provides a mock function for the type MockRepositoriesService
func (_mock *MockRepositoriesService) GetReleaseByTag(ctx context.Context, owner string, repo string, tag string) (*github.RepositoryRelease, *github.Response, error) {
	ret := _mock.Called(ctx, owner, repo, tag)

	if len(ret) == 0 {
		panic("no return value specified for GetReleaseByTag")
	}

	var r0 *github.RepositoryRelease
	var r1 *github.Response
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (*github.RepositoryRelease, *github.Response, error)); ok {
		return returnFunc(ctx, owner, repo, tag)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) *github.RepositoryRelease); ok {
		r0 = returnFunc(ctx, owner, repo, tag)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*github.RepositoryRelease)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) *github.Response); ok {
		r1 = returnFunc(ctx, owner, repo, tag)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*github.Response)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string, string) error); ok {
		r2 = returnFunc(ctx, owner, repo, tag)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockRepositoriesService_GetReleaseByTag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetReleaseByTag'
type MockRepositoriesService_GetReleaseByTag_Call struct {
	*mock.Call
}

// GetReleaseByTag is a helper method to define mock.On call
//   - ctx context.Context
//   - owner string
//   - repo string
//   - tag string
func (_e *MockRepositoriesService_Expecter) GetReleaseByTag(ctx interface{}, owner interface{}, repo interface{}, tag interface{}) *MockRepositoriesService_GetReleaseByTag_Call {
	return &MockRepositoriesService_GetReleaseByTag_Call{Call: _e.mock.On("GetReleaseByTag", ctx, owner, repo, tag)}
}

func (_c *MockRepositoriesService_GetReleaseByTag_Call) Run(run func(ctx context.Context, owner string, repo string, tag string)) *MockRepositoriesService_GetReleaseByTag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRepositoriesService_GetReleaseByTag_Call) Return(repositoryRelease *github.RepositoryRelease, response *github.Response, err error) *MockRepositoriesService_GetReleaseByTag_Call {
	_c.Call.Return(repositoryRelease, response, err)
	return _c
}

func (_c *MockRepositoriesService_GetReleaseByTag_Call) RunAndReturn(run func(ctx context.Context, owner string, repo string, tag string) (*github.RepositoryRelease, *github.Response, error)) *MockRepositoriesService_GetReleaseByTag_Call {
	_c.Call.Return(run)
	return _c
}

// UploadReleaseAsset provides a mock function for the type MockRepositoriesService
func (_mock *MockRepositoriesService) UploadReleaseAsset(ctx context.Context, owner string, repo string, id int64, opt *github.UploadOptions, file *os.File) (*github.ReleaseAsset, *github.Response, error) {
	ret := _mock.Called(ctx, owner, repo, id, opt, file)

	if len(ret) == 0 {
		panic("no return value specified for UploadReleaseAsset")
	}

	var r0 *github.ReleaseAsset
	var r1 *github.Response
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int64, *github.UploadOptions, *os.File) (*github.ReleaseAsset, *github.Response, error)); ok {
		return returnFunc(ctx, owner, repo, id, opt, file)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int64, *github.UploadOptions, *os.File) *github.ReleaseAsset); ok {
		r0 = returnFunc(ctx, owner, repo, id, opt, file)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*github.ReleaseAsset)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, int64, *github.UploadOptions, *os.File) *github.Response); ok {
		r1 = returnFunc(ctx, owner, repo, id, opt, file)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*github.Response)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string, int64, *github.UploadOptions, *os.File) error); ok {
		r2 = returnFunc(ctx, owner, repo, id, opt, file)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockRepositoriesService_UploadReleaseAsset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadReleaseAsset'
type MockRepositoriesService_UploadReleaseAsset_Call struct {
	*mock.Call
}

// UploadReleaseAsset is a helper method to define mock.On call
//   - ctx context.Context
//   - owner string
//   - repo string
//   - id int64
//   - opt *github.UploadOptions
//   - file *os.File
func (_e *MockRepositoriesService_Expecter) UploadReleaseAsset(ctx interface{}, owner interface{}, repo interface{}, id interface{}, opt interface{}, file interface{}) *MockRepositoriesService_UploadReleaseAsset_Call {
	return &MockRepositoriesService_UploadReleaseAsset_Call{Call: _e.mock.On("UploadReleaseAsset", ctx, owner, repo, id, opt, file)}
}

func (_c *MockRepositoriesService_UploadReleaseAsset_Call) Run(run func(ctx context.Context, owner string, repo string, id int64, opt *github.UploadOptions, file *os.File)) *MockRepositoriesService_UploadReleaseAsset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		var arg4 *github.UploadOptions
		if args[4] != nil {
			arg4 = args[4].(*github.UploadOptions)
		}
		var arg5 *os.File
		if args[5] != nil {
			arg5 = args[5].(*os.File)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockRepositoriesService_UploadReleaseAsset_Call) Return(releaseAsset *github.ReleaseAsset, response *github.Response, err error) *MockRepositoriesService_UploadReleaseAsset_Call {
	_c.Call.Return(releaseAsset, response, err)
	return _c
}

func (_c *MockRepositoriesService_UploadReleaseAsset_Call) RunAndReturn(run func(ctx context.Context, owner string, repo string, id int64, opt *github.UploadOptions, file *os.File) (*github.ReleaseAsset, *github.Response, error)) *MockRepositoriesService_UploadReleaseAsset_Call {
	_c.Call.Return(run)
	return _c
}
