name: lint

on:
  pull_request:
    branches: [master]
    paths:
      - .github/workflows/lint.yaml
      - '**.go'
  push:
    branches: [master]
    paths:
      - .github/workflows/lint.yaml
      - '**.go'

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: golangci/golangci-lint-action@v2
        with:
          version: v1.37.1
