name: lint

on:
  pull_request:
    branches: [master]
    paths:
      - '**.go'
      - .github/workflows/lint.yaml
  push:
    branches: [master]
    paths:
      - '**.go'
      - .github/workflows/lint.yaml

jobs:
  golangci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: golangci/golangci-lint-action@v2
        with:
          version: v1.37.1
