name: test

on:
  pull_request:
    branches: [master]
    paths:
      - .github/workflows/test.yaml
      - pkg/**
      - go.*
  push:
    branches: [master]
    paths:
      - .github/workflows/test.yaml
      - pkg/**
      - go.*

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version: 1.15
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            go-
      - run: make test
      - uses: codecov/codecov-action@v1
