name: wait-for-workflows

on:
  pull_request:

jobs:
  wait-for-workflows:
    runs-on: ubuntu-slim
    timeout-minutes: 15
    steps:
      - uses: int128/wait-for-workflows-action@8bdaaf8a9404db4d8ffd7a12a09b3675ee1f48e3 # v1.80.0
